### ISSUE TITLE
Feature request: icons column are the same as in Apache

### ISSUE THREAD

**Issue by aGGre55or** [aperezdc/ngx-fancyindex#67]
Organizations and companies in Russia are obliged to provide information about their activities on the public. Many uses for this httpd index. Column with the icon allows to distinguish between documents. When we are using Nginx we lose this opportunity. Fancyindex doesn't help in this. Moreover directory differ only in the symbol "/". See attach for examples.

![02-03-2017_arpit_httpd](https://cloud.githubusercontent.com/assets/3582394/23497462/26230838-ff34-11e6-9574-31a8de1f2ced.jpg)

![02-03-2017_arpit_fancyindex](https://cloud.githubusercontent.com/assets/3582394/23497495/4ed36944-ff34-11e6-872f-2303d3c5fbc3.jpg)

**Comment by aperezdc** [comment]
@aGGre55or: If you want icons for entries, you can make your theme add them. For example [this theme](https://github.com/TheInsomniac/Nginx-Fancyindex-Theme) has icons, which get added by using [suffix CSS selectors](https://github.com/TheInsomniac/Nginx-Fancyindex-Theme/blob/master/css/fancyindex_Icons.css#L187).

Because using CSS for theming is already possible, I think it is better to not add specific support in the Fancyindex module.
